import { Question } from '../types/index.js';

const ISO = new Date('2026-01-01').toISOString();

// Deterministic seeded PRNG (mulberry32) so each question's option order is stable
// across server restarts and identical on every call (critical for scoring consistency).
function hashSeed(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}
function mulberry32(seed: number) {
  let a = seed >>> 0;
  return function () {
    a |= 0; a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
// Deterministically permute a question's options so the correct answer lands in a
// varied position. Same question id -> same option order everywhere (stable for scoring).
function shuffleOptions(q: Question): Question {
  const order = [0, 1, 2, 3];
  const rng = mulberry32(hashSeed(q.id));
  for (let i = 3; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [order[i], order[j]] = [order[j], order[i]];
  }
  const opts = [q.option_a, q.option_b, q.option_c, q.option_d];
  const letters = ['A', 'B', 'C', 'D'] as const;
  const correctIdx = letters.indexOf(q.correct_answer);
  const newOpts = order.map((i) => opts[i]);
  const newCorrectIdx = order.indexOf(correctIdx);
  return {
    ...q,
    option_a: newOpts[0],
    option_b: newOpts[1],
    option_c: newOpts[2],
    option_d: newOpts[3],
    correct_answer: letters[newCorrectIdx],
  };
}

const RAW_QUESTIONS: Question[] = [
  {
    id: 'q-1',
    question: 'A model scores 99.8% on training data but worse than random guessing on unseen test data. What is the most likely cause?',
    option_a: 'Severe overfitting — it memorized training noise instead of learning general patterns.',
    option_b: 'Underfitting — the network had too few layers to capture the pattern.',
    option_c: 'The learning rate was exactly optimal, causing zero generalization.',
    option_d: 'The test set was accidentally larger than the training set.',
    correct_answer: 'A',
    explanation: 'Overfitting: the model memorizes quirks/noise in training data rather than generalizable patterns, so it fails on new data.',
    topic: 'Machine Learning',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-2',
    question: 'When an LLM confidently cites a research paper that does not exist, this behavior is called:',
    option_a: 'Gradient explosion',
    option_b: 'Token leakage',
    option_c: 'Hallucination',
    option_d: 'Embedding drift',
    correct_answer: 'C',
    explanation: 'Hallucination: LLMs produce plausible-sounding but factually false output because they predict likely token sequences, not verified facts.',
    topic: 'Generative AI',
    difficulty: 'Easy',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-3',
    question: 'In a Transformer, what does the self-attention mechanism fundamentally compute?',
    option_a: 'A fixed lookup table of word frequencies per language.',
    option_b: 'Dynamic weights representing how much each token relates to every other token.',
    option_c: 'The total number of parameters in the model.',
    option_d: 'A checksum used to verify training data integrity.',
    correct_answer: 'B',
    explanation: 'Self-attention lets each token weigh the relevance of every other token regardless of distance, capturing contextual relationships.',
    topic: 'LLMs',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-4',
    question: 'Which statement best distinguishes Narrow AI from Artificial General Intelligence (AGI)?',
    option_a: 'Narrow AI uses GPUs; AGI requires quantum hardware.',
    option_b: 'Narrow AI is open-source; AGI is always proprietary.',
    option_c: 'Narrow AI excels at a specific task; AGI can flexibly learn any intellectual task a human can.',
    option_d: 'Narrow AI runs offline; AGI requires constant internet.',
    correct_answer: 'C',
    explanation: 'All current AI (ChatGPT, AlphaGo, autopilot) is Narrow AI — specialized. AGI is a theoretical system with human-level general reasoning.',
    topic: 'AI Basics',
    difficulty: 'Easy',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-5',
    question: 'An autonomous car braked suddenly on an open highway after mistaking the low yellow harvest moon for a traffic light. This is best described as:',
    option_a: 'A firmware bug in the braking controller.',
    option_b: 'An Out-of-Distribution (OOD) visual edge case absent from training data.',
    option_c: 'A GPS clock synchronization error.',
    option_d: 'An adversarial patch placed on the road.',
    correct_answer: 'B',
    explanation: 'OOD edge cases are rare visual scenarios not represented in training data, causing vision models to misclassify in the real world.',
    topic: 'Real-world AI',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-6',
    question: 'Setting temperature to 0.0 when sampling from an LLM causes the output to:',
    option_a: 'Become strictly deterministic, always picking the highest-probability token.',
    option_b: 'Become more creative and diverse than at temperature 1.0.',
    option_c: 'Repeat the same word forever regardless of context.',
    option_d: 'Disable safety filters automatically.',
    correct_answer: 'A',
    explanation: 'Temperature 0 = greedy decoding: the model always selects the top-probability token, making output deterministic and reproducible.',
    topic: 'LLMs',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-7',
    question: 'Why are Convolutional Neural Networks (CNNs) better than plain MLPs for image tasks?',
    option_a: 'CNNs can read PNG files while MLPs cannot.',
    option_b: 'CNNs use a single global weight matrix with no spatial structure.',
    option_c: 'CNNs exploit 2D spatial locality and share weights across sliding kernels, reducing parameters.',
    option_d: 'CNNs skip backpropagation entirely during training.',
    correct_answer: 'C',
    explanation: 'CNNs preserve spatial hierarchy (nearby pixels are related) and share weights across convolution filters, detecting edges/textures with far fewer parameters than fully connected MLPs.',
    topic: 'Computer Vision',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-8',
    question: 'A "vector embedding" in modern NLP/search is best described as:',
    option_a: 'A hidden copyright watermark inserted into generated text.',
    option_b: 'A high-dimensional numeric vector where semantically similar concepts sit close together.',
    option_c: 'A compressed archive of the training dataset.',
    option_d: 'A CSS class used to format paragraphs.',
    correct_answer: 'B',
    explanation: 'Embeddings map text/images into vector spaces where semantic similarity = small cosine distance (e.g. "doctor" near "hospital").',
    topic: 'NLP',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-9',
    question: 'Training loss suddenly shows "NaN" on epoch 4. The most common cause is:',
    option_a: 'Exploding gradients caused by an excessively high learning rate.',
    option_b: 'Running out of disk space for checkpoints.',
    option_c: 'Using too many CPU threads in the dataloader.',
    option_d: 'The optimizer having too little momentum.',
    correct_answer: 'A',
    explanation: 'Exploding gradients: gradients grow exponentially through backprop, causing numeric overflow (infinity/NaN). Gradient clipping or a lower learning rate fixes it.',
    topic: 'Machine Learning',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-10',
    question: 'RAG (Retrieval-Augmented Generation) primarily reduces which LLM problem?',
    option_a: 'High inference latency on long prompts.',
    option_b: 'The cost of storing model weights.',
    option_c: 'Hallucination, by retrieving relevant facts/documents and feeding them to the LLM to ground its answer.',
    option_d: 'The need for tokenization of the prompt.',
    correct_answer: 'C',
    explanation: 'RAG searches a knowledge base for relevant snippets and injects them into the prompt, grounding the LLM answer in real data and reducing hallucinations.',
    topic: 'Generative AI',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-11',
    question: 'The Turing Test (1950) is designed to evaluate whether:',
    option_a: 'A model can beat a human in chess.',
    option_b: 'An algorithm can factor large semiprimes efficiently.',
    option_c: 'A program can be formally verified for correctness.',
    option_d: 'An interrogator can distinguish a computer\'s responses from a human\'s.',
    correct_answer: 'D',
    explanation: 'Turing\'s "Imitation Game" tests whether a machine produces natural responses indistinguishable from a human across text conversation.',
    topic: 'AI Basics',
    difficulty: 'Easy',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-12',
    question: 'For a model screening patients for a life-threatening contagious disease, which metric should be prioritized?',
    option_a: 'High Precision, to minimize false alarms.',
    option_b: 'High Recall (Sensitivity), so few sick patients are missed.',
    option_c: 'Low latency per inference.',
    option_d: 'High training accuracy on the full dataset.',
    correct_answer: 'B',
    explanation: 'In disease screening, a False Negative (sending a sick person home) is catastrophic. High Recall catches virtually all true positives.',
    topic: 'Machine Learning',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-13',
    question: 'Why do modern LLMs use subword tokenization (e.g. Byte-Pair Encoding) instead of whole words or characters?',
    option_a: 'Subwords balance vocabulary size and gracefully handle typos, rare words, and morphology.',
    option_b: 'Whole-word tokenization is forbidden by Unicode standards.',
    option_c: 'Characters cannot be encoded in UTF-8 efficiently.',
    option_d: 'Subwords guarantee zero information loss during compression.',
    correct_answer: 'A',
    explanation: 'BPE keeps frequent words as single tokens while decomposing rare/unknown words into smaller subword units — a finite vocabulary that still generalizes.',
    topic: 'NLP',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-14',
    question: 'How do image diffusion models (e.g. Stable Diffusion) generate images from text?',
    option_a: 'They retrieve and collage matching images from a search engine.',
    option_b: 'They render the scene in a headless 3D game engine.',
    option_c: 'They start from random Gaussian noise and iteratively subtract predicted noise guided by text embeddings.',
    option_d: 'They compute the Fourier transform of the audio of the prompt.',
    correct_answer: 'C',
    explanation: 'Diffusion models reverse a noising process: trained to predict and remove noise step-by-step from pure static until a sharp image emerges, conditioned on text.',
    topic: 'Generative AI',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-15',
    question: 'An AI recruiting tool trained on 10 years of past resumes started penalizing female candidates. The root cause is:',
    option_a: 'A bug in the if/else scoring logic.',
    option_b: 'Historical bias in the training data reflecting past male-dominated hiring.',
    option_c: 'The model using 32-bit instead of 64-bit floats.',
    option_d: 'Resumes being submitted as PDF rather than DOCX.',
    correct_answer: 'B',
    explanation: 'A real case (Amazon, 2018). Models mirror biases in historical data unless deliberately audited and mitigated — garbage in, garbage out.',
    topic: 'Real-world AI',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-16',
    question: 'The fundamental purpose of a loss function in training is to:',
    option_a: 'Log the electricity cost of GPU training.',
    option_b: 'Measure how many lines of code were deprecated.',
    option_c: 'Quantify how far the model\'s prediction is from ground truth, so gradients can adjust weights.',
    option_d: 'Count the number of parameters in the network.',
    correct_answer: 'C',
    explanation: 'The loss scores prediction error; optimizers compute its gradient w.r.t. weights and update parameters to minimize it.',
    topic: 'Machine Learning',
    difficulty: 'Easy',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-17',
    question: 'The key difference between image classification and object detection is that detection also:',
    option_a: 'Predicts the location of each object via bounding boxes, not just a single label per image.',
    option_b: 'Works only on grayscale images.',
    option_c: 'Requires no labeled training data.',
    option_d: 'Uses a smaller input resolution.',
    correct_answer: 'A',
    explanation: 'Classification labels the whole image ("dog"); detection finds multiple objects and their bounding-box coordinates.',
    topic: 'Computer Vision',
    difficulty: 'Easy',
    is_active: true,
    created_at: ISO,
  },
  // __MORE_Q__
  {
    id: 'q-18',
    question: 'Fine-tuning a pre-trained foundation model means:',
    option_a: 'Deleting most of its weights to shrink it.',
    option_b: 'Training it further on specialized target-domain data to adapt it to a specific task.',
    option_c: 'Translating its weights from Python to C++.',
    option_d: 'Lowering its learning rate to exactly zero.',
    correct_answer: 'B',
    explanation: 'Fine-tuning = transfer learning: take a broad pre-trained model and continue training on specialized data (legal, medical, etc.) for a target task.',
    topic: 'LLMs',
    difficulty: 'Easy',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-19',
    question: 'RLHF (Reinforcement Learning from Human Feedback) is used to:',
    option_a: 'Speed up inference by caching responses.',
    option_b: 'Compress model weights for mobile deployment.',
    option_c: 'Train a reward model from human rankings that guides the LLM toward helpful, aligned answers.',
    option_d: 'Generate more pretraining tokens from the web.',
    correct_answer: 'C',
    explanation: 'RLHF aligns raw completion models into helpful assistants by training a reward model on human preference data, then optimizing the LLM against it.',
    topic: 'AI Basics',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-20',
    question: 'A model aces a static benchmark yet fails in production mainly because:',
    option_a: 'The real world is non-stationary, noisy, and full of unseen edge cases the benchmark never covered.',
    option_b: 'Gravity interferes with silicon transistors in production.',
    option_c: 'IEEE rules forbid high accuracy in live systems.',
    option_d: 'JavaScript floating-point rounding corrupts predictions.',
    correct_answer: 'A',
    explanation: 'Benchmarks are static and narrow; production data drifts over time and contains adversarial/edge inputs, causing concept drift and degraded accuracy.',
    topic: 'Real-world AI',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-21',
    question: 'Which is the most direct cause of high bias (underfitting) in a model?',
    option_a: 'The model is too simple to capture the underlying pattern in the data.',
    option_b: 'The model is too complex and memorizes noise.',
    option_c: 'The training set is larger than the test set.',
    option_d: 'The optimizer used too many epochs.',
    correct_answer: 'A',
    explanation: 'High bias = underfitting: the model class is too simple (e.g. linear for nonlinear data) to represent the true relationship.',
    topic: 'Machine Learning',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-22',
    question: 'Which is the most direct cause of high variance (overfitting)?',
    option_a: 'Too little training data combined with an overly complex model.',
    option_b: 'A learning rate that is too small.',
    option_c: 'Using batch normalization.',
    option_d: 'Having a single feature in the input.',
    correct_answer: 'A',
    explanation: 'High variance = overfitting: a complex model fits noise in small data, generalizing poorly. Fix with more data, regularization, or a simpler model.',
    topic: 'Machine Learning',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-23',
    question: 'In a Transformer block, the "multi-head" part of multi-head attention allows the model to:',
    option_a: 'Run on multiple GPUs in parallel automatically.',
    option_b: 'Capture different relation types (syntactic, semantic) simultaneously via parallel attention subspaces.',
    option_c: 'Memorize the entire training corpus.',
    option_d: 'Skip the feed-forward layers entirely.',
    correct_answer: 'B',
    explanation: 'Multiple heads project into different subspaces, letting the model attend to different kinds of relationships in parallel before concatenating results.',
    topic: 'LLMs',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-24',
    question: 'Gradient Descent updates a weight using which rule?',
    option_a: 'w = w + learning_rate * gradient',
    option_b: 'w = w - learning_rate * gradient',
    option_c: 'w = w * gradient + bias',
    option_d: 'w = gradient - learning_rate * w',
    correct_answer: 'B',
    explanation: 'Gradient descent moves opposite to the gradient of the loss: w ← w − η·∇L, reducing the loss each step.',
    topic: 'Machine Learning',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-25',
    question: 'Which is the best example of "data augmentation" for an image classifier?',
    option_a: 'Adding more fully-connected layers to the network.',
    option_b: 'Randomly flipping, rotating, and cropping existing images to synthetically expand the training set.',
    option_c: 'Increasing the learning rate over training.',
    option_d: 'Removing the validation set.',
    correct_answer: 'B',
    explanation: 'Augmentation creates new training samples via label-preserving transforms (flip, crop, rotate, color jitter), improving generalization without collecting new data.',
    topic: 'Computer Vision',
    difficulty: 'Easy',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-26',
    question: 'A confusion matrix shows 90 true positives, 10 false positives, 30 false negatives, 870 true negatives. The recall (sensitivity) is:',
    option_a: '90 / (90 + 10) = 0.90',
    option_b: '90 / (90 + 30) = 0.75',
    option_c: '90 / (90 + 10 + 30 + 870) = 0.09',
    option_d: '870 / (870 + 30) = 0.97',
    correct_answer: 'B',
    explanation: 'Recall = TP / (TP + FN) = 90 / 120 = 0.75. It measures the fraction of actual positives correctly identified.',
    topic: 'Machine Learning',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-27',
    question: 'What is the main purpose of dropout during neural network training?',
    option_a: 'To speed up training by dropping entire layers permanently.',
    option_b: 'To randomly deactivate neurons during training, preventing co-adaptation and reducing overfitting.',
    option_c: 'To drop the learning rate to zero at the end.',
    option_d: 'To remove the bias term from each layer.',
    correct_answer: 'B',
    explanation: 'Dropout randomly zeros activations during training, forcing the network to learn redundant robust features — a regularization technique against overfitting.',
    topic: 'Machine Learning',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-28',
    question: 'Word2vec and GloVe produce embeddings by training on the principle that:',
    option_a: 'Words that appear in similar contexts have similar meanings ("distributional hypothesis").',
    option_b: 'Words must be sorted alphabetically before training.',
    option_c: 'Each word maps to a unique prime number.',
    option_d: 'Embeddings must have exactly 2 dimensions for plotting.',
    correct_answer: 'A',
    explanation: 'Both leverage the distributional hypothesis: a word\'s meaning is captured by the company it keeps, learned via co-occurrence statistics.',
    topic: 'NLP',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-29',
    question: 'In a Generative Adversarial Network (GAN), the generator and discriminator are trained to:',
    option_a: 'Cooperate to compress the input dataset.',
    option_b: 'Compete: the generator fakes data, the discriminator tries to detect fakes, each improving the other.',
    option_c: 'Share weights to reduce total parameters.',
    option_d: 'Memorize the same training images.',
    correct_answer: 'B',
    explanation: 'GANs use a minimax game: G learns to fool D, D learns to catch G. At equilibrium, G produces realistic samples.',
    topic: 'Generative AI',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-30',
    question: 'Why is the "softmax" function used at the output of a multi-class classifier?',
    option_a: 'It converts raw logits into a probability distribution that sums to 1 across classes.',
    option_b: 'It makes all outputs exactly 0 or 1 (hard labels).',
    option_c: 'It removes the largest logit to stabilize training.',
    option_d: 'It scales inputs to a fixed range of 0–255.',
    correct_answer: 'A',
    explanation: 'Softmax exponentiates and normalizes logits into probabilities summing to 1, enabling interpretable class scores and cross-entropy training.',
    topic: 'Machine Learning',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-31',
    question: 'A language model "context window" refers to:',
    option_a: 'The total disk space used to store weights.',
    option_b: 'The maximum number of tokens the model can attend to in a single forward pass.',
    option_c: 'The number of layers in the network.',
    option_d: 'The number of training examples seen so far.',
    correct_answer: 'B',
    explanation: 'The context window is the max tokens (prompt + generated) the model processes at once; exceeding it causes truncation or errors.',
    topic: 'LLMs',
    difficulty: 'Easy',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-32',
    question: 'Transfer learning works best when:',
    option_a: 'The source and target tasks share relevant low-level features (e.g. edges, language structure).',
    option_b: 'The source and target domains have nothing in common.',
    option_c: 'The target dataset is much larger than the source.',
    option_d: 'The model is randomly re-initialized before transfer.',
    correct_answer: 'A',
    explanation: 'Knowledge transfers when source features are reusable for the target (e.g. ImageNet edges help medical imaging); unrelated domains transfer poorly.',
    topic: 'Machine Learning',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-33',
    question: 'Batch Normalization helps training primarily by:',
    option_a: 'Normalizing layer inputs per mini-batch, stabilizing activations and allowing higher learning rates.',
    option_b: 'Removing the need for any activation function.',
    option_c: 'Doubling the number of training epochs.',
    option_d: 'Eliminating the need for a validation set.',
    correct_answer: 'A',
    explanation: 'BatchNorm normalizes activations to zero mean/unit variance per batch, reducing internal covariate shift and smoothing the loss landscape.',
    topic: 'Machine Learning',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-34',
    question: 'In NLP, "named entity recognition" (NER) is the task of:',
    option_a: 'Generating new names for fictional characters.',
    option_b: 'Classifying the sentiment of a sentence.',
    option_c: 'Translating text between languages.',
    option_d: 'Locating and classifying entities (persons, orgs, dates, locations) in text.',
    correct_answer: 'D',
    explanation: 'NER tags spans of text with entity categories (PER, ORG, GPE, DATE), enabling information extraction from documents.',
    topic: 'NLP',
    difficulty: 'Easy',
    is_active: true,
    created_at: ISO,
  },
  // __MORE_Q2__
  {
    id: 'q-35',
    question: 'Which problem does "attention" in seq2seq models originally solve over plain RNN encoders?',
    option_a: 'It lets the decoder focus on relevant source positions instead of a single fixed-length vector, improving long-sentence translation.',
    option_b: 'It removes the need for an encoder entirely.',
    option_c: 'It makes the model train without any data.',
    option_d: 'It converts the model into a classifier.',
    correct_answer: 'A',
    explanation: 'Bahdanau attention lets the decoder dynamically weigh source hidden states, overcoming the bottleneck of compressing a whole sentence into one vector.',
    topic: 'NLP',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-36',
    question: 'A model trained on English-only reviews is deployed on Spanish reviews and accuracy collapses. This is best described as:',
    option_a: 'Concept drift due to a shift in input distribution (covariate shift).',
    option_b: 'Label noise in the training set.',
    option_c: 'Overfitting to the English vocabulary only.',
    option_d: 'Both A and C.',
    correct_answer: 'D',
    explanation: 'The input distribution changed (covariate shift) and the model overfits English-specific features — both contribute to the cross-domain failure.',
    topic: 'Real-world AI',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-37',
    question: 'Which is the correct ordering of the supervised-learning pipeline stages?',
    option_a: 'Deploy → collect data → train → evaluate.',
    option_b: 'Collect data → engineer features → train → evaluate → deploy → monitor.',
    option_c: 'Train → deploy → collect data → evaluate.',
    option_d: 'Evaluate → train → collect data → deploy.',
    correct_answer: 'B',
    explanation: 'Standard ML pipeline: data collection, feature engineering, training, evaluation, deployment, then ongoing monitoring for drift.',
    topic: 'Machine Learning',
    difficulty: 'Easy',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-38',
    question: 'The key idea behind "few-shot" prompting of an LLM is to:',
    option_a: 'Train the model on a few new examples via backprop.',
    option_b: 'Show a few input/output examples in the prompt to steer the model\'s output format without weight updates.',
    option_c: 'Run the model a few times and average outputs.',
    option_d: 'Reduce the model\'s context window.',
    correct_answer: 'B',
    explanation: 'Few-shot prompting provides demonstrations in-context; the model learns the pattern from examples without any gradient updates — in-context learning.',
    topic: 'LLMs',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-39',
    question: 'In computer vision, "data augmentation" that flips an image horizontally is label-preserving for which task?',
    option_a: 'Detecting whether a tumor is on the left vs right lung.',
    option_b: 'Classifying whether the image contains a cat.',
    option_c: 'Reading the digits on a car\'s license plate.',
    option_d: 'Recognizing the text on a road sign.',
    correct_answer: 'B',
    explanation: 'A cat is still a cat when flipped, so the label is preserved. But left/right orientation, digits, and text are NOT flip-invariant — augmentation would corrupt labels there.',
    topic: 'Computer Vision',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-40',
    question: 'A "prompt injection" attack against an LLM agent is one where the attacker:',
    option_a: 'Physically damages the GPU.',
    option_b: 'Embeds hidden instructions in data the LLM reads, overriding the system instructions.',
    option_c: 'Steals the model weights from the server.',
    option_d: 'Disables the model\'s tokenizer.',
    correct_answer: 'B',
    explanation: 'Prompt injection hides malicious instructions in retrieved documents/web pages the LLM ingests, hijacking its behavior — a top security risk for LLM agents.',
    topic: 'Real-world AI',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-41',
    question: 'The "curse of dimensionality" refers to the fact that as feature dimensions grow:',
    option_a: 'Models train faster because gradients are larger.',
    option_b: 'Data becomes sparse in high-dimensional space, so distance/similarity measures lose meaning and more data is needed.',
    option_c: 'The model needs fewer training examples.',
    option_d: 'Accuracy always improves.',
    correct_answer: 'B',
    explanation: 'In high dimensions, points are far apart and nearly equidistant, so kNN/clustering/distance-based methods degrade and require exponentially more data.',
    topic: 'Machine Learning',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-42',
    question: 'Why is cross-entropy loss (not MSE) typically used for classification outputs?',
    option_a: 'MSE cannot be computed on numbers.',
    option_b: 'Cross-entropy penalizes wrong-but-confident predictions much more sharply, matching the softmax probability output.',
    option_c: 'Cross-entropy trains with no data.',
    option_d: 'MSE requires a GPU and cross-entropy does not.',
    correct_answer: 'B',
    explanation: 'Cross-entropy with softmax gives large gradients for confident wrong answers, speeding and stabilizing classification training; MSE gives weak gradients near saturation.',
    topic: 'Machine Learning',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-43',
    question: 'A retrieval system returns the top-100 most similar documents by cosine similarity. This is an example of:',
    option_a: 'Supervised classification.',
    option_b: 'Reinforcement learning.',
    option_c: 'Nearest-neighbor (vector similarity) search over embeddings.',
    option_d: 'Decision-tree induction.',
    correct_answer: 'C',
    explanation: 'Embedding-based retrieval ranks candidates by cosine distance in vector space — a nearest-neighbor search, the backbone of semantic search and RAG.',
    topic: 'NLP',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-44',
    question: 'In a diffusion model, the "scheduler" controls:',
    option_a: 'The number of GPU threads used per step.',
    option_b: 'The noise variance and number of denoising steps used to go from noise to image.',
    option_c: 'The learning rate of the text encoder.',
    option_d: 'The size of the training dataset.',
    correct_answer: 'B',
    explanation: 'The scheduler defines the noise schedule (β_t) and step count; more steps yield higher-quality images at the cost of slower generation.',
    topic: 'Generative AI',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-45',
    question: 'A "tokenizer" in an LLM pipeline is responsible for:',
    option_a: 'Splitting text into subword tokens and mapping each to an integer id the model can process.',
    option_b: 'Tokenizing credit-card payments for the API.',
    option_c: 'Rendering the model\'s output as images.',
    option_d: 'Compressing the model weights for download.',
    correct_answer: 'A',
    explanation: 'The tokenizer converts raw text ↔ token ids (e.g. BPE). It defines the vocabulary the model was trained on and is essential for input/output.',
    topic: 'LLMs',
    difficulty: 'Easy',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-46',
    question: 'Which situation is a classic example of "label leakage" in training data?',
    option_a: 'Including a feature that encodes the target (e.g. "is_fraud" column) among the inputs.',
    option_b: 'Using a small learning rate.',
    option_c: 'Having more test data than training data.',
    option_d: 'Applying dropout to the input layer.',
    correct_answer: 'A',
    explanation: 'Label leakage lets the model cheat by seeing the answer in its inputs, producing unrealistically high validation accuracy that collapses in production.',
    topic: 'Real-world AI',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-47',
    question: 'A k-NN classifier with k=1 typically suffers from:',
    option_a: 'High bias and severe underfitting.',
    option_b: 'High variance — it memorizes the training set and is sensitive to noise/outliers.',
    option_c: 'Inability to classify more than two classes.',
    option_d: 'Zero training error and zero test error always.',
    correct_answer: 'B',
    explanation: 'k=1 fits each training point exactly, so the decision boundary is jagged and overfits noise; larger k smooths it (bias↑, variance↓).',
    topic: 'Machine Learning',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-48',
    question: 'The main reason LLMs are "aligned" with techniques like RLHF/constitutional AI is to:',
    option_a: 'Reduce the model\'s parameter count.',
    option_b: 'Make the model produce responses that are helpful, honest, and harmless per human intent.',
    option_c: 'Speed up tokenization.',
    option_d: 'Increase the context window size.',
    correct_answer: 'B',
    explanation: 'Alignment steers raw pretrained models toward safe, useful behavior aligned with human values, reducing harmful/unhelpful outputs.',
    topic: 'AI Basics',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-49',
    question: 'A model achieves 95% accuracy on an imbalanced dataset where 90% of samples are the majority class. The accuracy is misleading because:',
    option_a: 'Accuracy is never a valid metric.',
    option_b: 'A trivial "always predict majority" classifier already gets 90%, so 95% may reflect little real learning of the minority class.',
    option_c: 'The model must be overfitting.',
    option_d: 'Accuracy cannot exceed 50% on any dataset.',
    correct_answer: 'B',
    explanation: 'On imbalanced data, accuracy is dominated by the majority class; use precision, recall, F1, or balanced accuracy to assess minority-class performance.',
    topic: 'Machine Learning',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-50',
    question: 'The biggest practical risk of deploying an LLM without guardrails in a customer-facing app is:',
    option_a: 'The model running out of disk space.',
    option_b: 'The model generating harmful, biased, or hallucinated content that the company is then responsible for.',
    option_c: 'The model training itself further without permission.',
    option_d: 'The model refusing to use electricity.',
    correct_answer: 'B',
    explanation: 'Unguarded LLMs can output toxic, biased, or false content at scale, creating legal, reputational, and safety risks — hence guardrails, filtering, and human review.',
    topic: 'Real-world AI',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-51',
    question: 'Which sorting algorithm has an average time complexity of O(n log n) but degrades to O(n²) on already-sorted input when using a naive pivot choice?',
    option_a: 'Bubble Sort',
    option_b: 'Quick Sort',
    option_c: 'Merge Sort',
    option_d: 'Heap Sort',
    correct_answer: 'B',
    explanation: 'Quick Sort averages O(n log n), but picking the first element as pivot on already-sorted data creates unbalanced partitions, degrading to O(n²). Merge Sort and Heap Sort stay O(n log n) worst-case.',
    topic: 'Algorithms',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-52',
    question: 'In SQL, which clause is used to filter rows AFTER a GROUP BY aggregation has been performed?',
    option_a: 'WHERE',
    option_b: 'FILTER',
    option_c: 'HAVING',
    option_d: 'ORDER BY',
    correct_answer: 'C',
    explanation: 'WHERE filters rows before grouping; HAVING filters the grouped/aggregated results. This is a common interview trap — HAVING works on aggregate functions like COUNT/SUM.',
    topic: 'Databases',
    difficulty: 'Easy',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-53',
    question: 'Which HTTP status code indicates that the requested resource has been permanently moved to a new URL?',
    option_a: '301',
    option_b: '302',
    option_c: '404',
    option_d: '500',
    correct_answer: 'A',
    explanation: '301 Moved Permanently signals a permanent redirect (browsers and search engines cache it). 302 is a temporary redirect, 404 is not found, 500 is a server error.',
    topic: 'Web',
    difficulty: 'Easy',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-54',
    question: 'What is the time complexity of inserting an element into a balanced binary search tree (e.g., AVL or Red-Black)?',
    option_a: 'O(1)',
    option_b: 'O(log n)',
    option_c: 'O(n)',
    option_d: 'O(n²)',
    correct_answer: 'B',
    explanation: 'A balanced BST maintains height O(log n), so search + insert take O(log n). An unbalanced BST can degrade to O(n) — which is why self-balancing trees exist.',
    topic: 'Data Structures',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-55',
    question: 'Which Git command creates a new branch AND immediately switches to it?',
    option_a: 'git branch <name>',
    option_b: 'git switch <name>',
    option_c: 'git checkout -b <name>',
    option_d: 'git merge <name>',
    correct_answer: 'C',
    explanation: '`git checkout -b <name>` creates and switches in one step. `git branch` only creates; `git switch` only switches an existing branch; `git merge` combines branches.',
    topic: 'Tools',
    difficulty: 'Easy',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-56',
    question: 'In object-oriented programming, which principle restricts direct access to an object\u2019s internal state and exposes it only through methods?',
    option_a: 'Inheritance',
    option_b: 'Polymorphism',
    option_c: 'Encapsulation',
    option_d: 'Abstraction',
    correct_answer: 'C',
    explanation: 'Encapsulation bundles data with the methods that operate on it and restricts direct field access (private fields + public getters/setters). Abstraction hides complexity behind an interface; the two are related but distinct.',
    topic: 'Programming',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-57',
    question: 'Which data structure is most appropriate for implementing an undo/redo feature in a text editor?',
    option_a: 'Queue',
    option_b: 'Hash Map',
    option_c: 'Two stacks',
    option_d: 'Binary Heap',
    correct_answer: 'C',
    explanation: 'Two stacks — one for undo history, one for redo — give O(1) push/pop. Undo pops from the undo stack and pushes onto the redo stack; redo reverses it.',
    topic: 'Data Structures',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-58',
    question: 'What does the acronym ACID stand for in the context of database transactions?',
    option_a: 'Atomicity, Consistency, Isolation, Durability',
    option_b: 'Accuracy, Concurrency, Integrity, Distribution',
    option_c: 'Atomicity, Caching, Indexing, Durability',
    option_d: 'Availability, Consistency, Identity, Distribution',
    correct_answer: 'A',
    explanation: 'ACID = Atomicity (all-or-nothing), Consistency (valid state), Isolation (concurrent txns don\u2019t interfere), Durability (committed data survives crashes). It is the gold standard for relational DBs.',
    topic: 'Databases',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-59',
    question: 'Which neural network architecture is best suited for processing sequential data such as time-series or natural language?',
    option_a: 'Convolutional Neural Network (CNN)',
    option_b: 'Recurrent Neural Network (RNN) / Transformer',
    option_c: 'Generative Adversarial Network (GAN)',
    option_d: 'Multi-Layer Perceptron (MLP)',
    correct_answer: 'B',
    explanation: 'RNNs and Transformers are designed for sequences — they model order and context. CNNs excel at images (spatial), GANs generate data, and plain MLPs ignore sequence structure.',
    topic: 'AI/ML',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-60',
    question: 'In REST API design, which HTTP method is idempotent — meaning multiple identical requests have the same effect as a single one?',
    option_a: 'POST',
    option_b: 'PATCH',
    option_c: 'PUT',
    option_d: 'CONNECT',
    correct_answer: 'C',
    explanation: 'PUT is idempotent: sending the same PUT twice replaces the resource with the same state, no extra effect. POST is non-idempotent (each call may create a new resource). PATCH is not strictly idempotent. CONNECT is for tunneling.',
    topic: 'Web',
    difficulty: 'Medium',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-61',
    question: 'In a Transformer self-attention layer, the attention weight applied to value vector v_j when querying with q_i is computed as:',
    option_a: 'softmax over j of (q_i \u00b7 k_j) / sqrt(d)',
    option_b: 'softmax over j of (q_i \u00b7 k_j)',
    option_c: 'sigmoid(q_i \u00b7 v_j)',
    option_d: 'max over j of (q_i \u00b7 k_j)',
    correct_answer: 'A',
    explanation: 'Scaled dot-product attention: weights = softmax_j((q_i \u00b7 k_j) / sqrt(d_k)), then sum of weights * v_j. The 1/sqrt(d_k) scaling prevents the softmax from saturating in high dimensions. Without scaling, gradients vanish.',
    topic: 'GenAI',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-62',
    question: 'Which statement about Large Language Model tokenizers is MOST accurate?',
    option_a: 'BPE tokenizers split text into whole words only, never subwords.',
    option_b: 'A token\u2019s id is fixed globally across every model, so "cat" is always the same id.',
    option_c: 'BPE merges are learned from a training corpus and the same word can tokenize differently depending on surrounding context and the learned merges.',
    option_d: 'SentencePiece and BPE are identical algorithms with different names.',
    correct_answer: 'C',
    explanation: 'BPE learns merge rules from corpus statistics; tokens are subword units and the same surface word can split differently based on context and the model\u2019s vocab. Token ids are model-specific (not global), and SentencePiece trains directly on raw text vs. BPE on pre-tokenized words.',
    topic: 'GenAI',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-63',
    question: 'In RLHF for LLMs, what does the trained reward model actually output, and how is it used during PPO?',
    option_a: 'It outputs the final answer text, which is concatenated to the prompt.',
    option_b: 'It outputs a scalar reward signal used to update the policy (LLM) via PPO, while a KL penalty keeps the policy close to the reference model.',
    option_c: 'It outputs token-level embeddings that replace the LLM\u2019s own embeddings.',
    option_d: 'It outputs a classification label (good/bad) used only to filter training data, with no policy update.',
    correct_answer: 'B',
    explanation: 'The reward model scores prompt-response pairs with a scalar. PPO uses it to update the LLM policy, regularized by a KL-divergence penalty against the frozen reference (pre-RLHF) model to prevent reward hacking and mode collapse.',
    topic: 'GenAI',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-64',
    question: 'Which BEST explains why temperature > 0 in LLM sampling increases output diversity but very low temperature approaches greedy decoding?',
    option_a: 'Temperature divides the logits before softmax; T -> 0 makes the distribution approach argmax (greedy), while higher T flattens it, sampling lower-ranked tokens more often.',
    option_b: 'Temperature adds noise to the token embeddings after the model has chosen them.',
    option_c: 'Temperature changes the model weights at inference time, producing a different model.',
    option_d: 'Temperature truncates the vocabulary to the top-k tokens regardless of probability.',
    correct_answer: 'A',
    explanation: 'Sampling uses softmax(logits / T). As T -> 0, the distribution concentrates on the top logit (greedy/argmax). Higher T flattens probabilities so non-top tokens get sampled more, increasing diversity. It operates on logits, not weights or embeddings.',
    topic: 'GenAI',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-65',
    question: 'Which technique BEST reduces hallucination in an LLM answering factual questions about a private document corpus, WITHOUT fine-tuning the model?',
    option_a: 'Increasing temperature to 1.5 so the model "explores" more answers.',
    option_b: 'Retrieval-Augmented Generation (RAG): embed relevant chunks, retrieve top-k by similarity, and condition the LLM on them in the prompt.',
    option_c: 'Prompting the model to "be creative" and invent details it is unsure about.',
    option_d: 'Removing the system prompt entirely.',
    correct_answer: 'B',
    explanation: 'RAG grounds generation in retrieved evidence, letting the LLM cite/extract from real chunks instead of relying on parametric memory. Higher temperature increases hallucination; removing the system prompt removes helpful guardrails.',
    topic: 'GenAI',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-66',
    question: 'In a ReAct-style agentic loop, what is the correct ordering of steps the agent repeats to solve a task with external tools?',
    option_a: 'Act -> Observe -> Think -> (repeat), where the model first calls a tool, then reasons about why, then sees output.',
    option_b: 'Think -> Act -> Observe -> (repeat), where the model reasons about the goal, chooses a tool/action, then incorporates the observation before the next thought.',
    option_c: 'Observe -> Think -> Act -> (repeat), where the model waits for tool output before it can reason at all.',
    option_d: 'Act -> Think -> Observe -> (repeat), identical to option A but renamed.',
    correct_answer: 'B',
    explanation: 'ReAct interleaves Reasoning (Thought) and Acting (tool calls) with Observations: Thought -> Action -> Observation -> Thought ... The reasoning guides tool choice; observations feed the next reasoning step. This is the backbone of most modern agent frameworks.',
    topic: 'Agentic AI',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-67',
    question: 'A core risk when giving an LLM agent the ability to execute arbitrary code or shell commands is prompt injection. Which mitigation is MOST effective in practice?',
    option_a: 'Asking the model nicely in the system prompt to never follow untrusted instructions.',
    option_b: 'Relying solely on the model\u2019s built-in instruction hierarchy, since modern LLMs cannot be jailbroken.',
    option_c: 'Principle of least privilege + sandboxing + human-in-the-loop approval for destructive actions + output validation, treating all tool outputs as untrusted data.',
    option_d: 'Increasing the model\u2019s temperature so it forgets injected instructions.',
    correct_answer: 'C',
    explanation: 'Prompt injection can override instructions via tool output, so defenses must be layered: run code in isolated sandboxes, scope credentials/permissions minimally, require human approval for irreversible actions, and validate outputs. No single prompt-level instruction is sufficient.',
    topic: 'Agentic AI',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-68',
    question: 'Which is the MOST accurate comparison between a fine-tuned small LLM and a large LLM used zero-shot with a good prompt for a narrow, well-defined task?',
    option_a: 'Fine-tuning is always worse because large models are universally better at everything.',
    option_b: 'A fine-tuned small model can match or beat a much larger zero-shot model on a narrow task (format, style, domain) at lower latency/cost, but loses generality outside that domain.',
    option_c: 'Fine-tuning only changes the tokenizer, not the model behavior.',
    option_d: 'Prompting a large model can never achieve consistent output formatting; only fine-tuning can.',
    correct_answer: 'B',
    explanation: 'Fine-tuning specializes a small model to a target distribution (tone, format, domain knowledge), often matching larger models on that task while being cheaper and faster. The trade-off is reduced flexibility on out-of-distribution inputs. Both approaches have valid use cases.',
    topic: 'GenAI',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-69',
    question: 'In an LLM agent using function-calling with multiple tools, which design choice BEST reduces the chance of the model calling the wrong tool or hallucinating tool arguments?',
    option_a: 'Giving every tool the same name so the model picks randomly.',
    option_b: 'Providing precise tool names, clear JSON schemas with descriptions, constrained enums/formats, and validating the model\u2019s emitted args before execution.',
    option_c: 'Removing all argument descriptions so the model has more freedom.',
    option_d: 'Letting the model invent its own tool schemas at runtime.',
    correct_answer: 'B',
    explanation: 'Tool-calling reliability comes from unambiguous schemas: descriptive names, typed parameters, enums for categorical args, and strict server-side validation (and retries) before the tool actually runs. Ambiguous schemas cause wrong-tool selection and malformed arguments.',
    topic: 'Agentic AI',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-70',
    question: 'Which statement about the KV-cache in autoregressive Transformer inference is CORRECT?',
    option_a: 'The KV-cache stores past keys/values so previously-computed tokens need not be recomputed each step; it grows with context length and is a major memory cost in long-context generation.',
    option_b: 'The KV-cache stores the model weights so they don\u2019t have to be loaded from disk each token.',
    option_c: 'The KV-cache is only used during training, never inference.',
    option_d: 'The KV-cache is fixed in size regardless of sequence length.',
    correct_answer: 'A',
    explanation: 'During generation, each new token attends to all past tokens; caching their K/V avoids recomputation. Memory scales with layers x heads x seq_len x head_dim, which is why long contexts are expensive and techniques like paged attention / quantized KV exist.',
    topic: 'GenAI',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-71',
    question: 'In a multi-agent system where a "planner" LLM decomposes a goal into subtasks handed to "worker" agents, which failure mode is MOST important to guard against?',
    option_a: 'The planner producing subtasks that are ambiguous, unbounded, or lack clear success criteria, causing workers to loop, duplicate work, or never terminate.',
    option_b: 'Workers finishing their subtasks too quickly.',
    option_c: 'The planner using too few tokens in its response.',
    option_d: 'The system using fewer than 10 agents regardless of task size.',
    correct_answer: 'A',
    explanation: 'Without well-scoped subtasks and termination/success criteria, multi-agent systems spiral: workers misinterpret goals, redo each other\u2019s work, or loop indefinitely. Mitigations include structured output schemas, verification steps, max-iteration limits, and a critic/summarizer role.',
    topic: 'Agentic AI',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-72',
    question: 'Which BEST explains why greedy decoding (always picking the highest-probability token) often produces repetitive, degenerate text, while nucleus (top-p) sampling helps?',
    option_a: 'Greedy decoding can get stuck in loops because it always commits to the local maximum, while top-p samples from the smallest token set whose cumulative probability >= p, allowing escape from repetition.',
    option_b: 'Greedy decoding uses a different model than sampling does.',
    option_c: 'Top-p forces the model to always pick the lowest-probability token.',
    option_d: 'Greedy decoding is mathematically impossible for Transformers.',
    correct_answer: 'A',
    explanation: 'Greedy/argmax decoding deterministically follows the highest logit, which can trap the model in repetitive cycles. Top-p (nucleus) sampling restricts the candidate pool to the smallest set with cumulative probability >= p, then samples within it - preserving coherence while allowing variation.',
    topic: 'GenAI',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-73',
    question: 'Which is the MOST accurate statement about quantizing an LLM (e.g., to 4-bit) for deployment?',
    option_a: '4-bit quantization always makes the model strictly more accurate than the original FP16 weights.',
    option_b: 'Quantization reduces memory footprint and often improves inference throughput at the cost of a small (usually acceptable) quality degradation, with techniques like GPTQ/AWQ/GGUF minimizing it.',
    option_c: 'Quantization changes the model\u2019s architecture (e.g., removes attention layers).',
    option_d: 'A quantized model cannot be served on any GPU, only on CPUs.',
    correct_answer: 'B',
    explanation: 'Quantization compresses weights to lower precision (e.g., INT4), cutting memory and bandwidth requirements. Modern methods (GPTQ, AWQ, GGUF, NF4) keep quality loss small. It does not alter architecture; quantized models run on GPUs, CPUs, and edge devices.',
    topic: 'GenAI',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-74',
    question: 'In an autonomous coding agent that edits files and runs tests in a loop, which design BEST balances autonomy and safety?',
    option_a: 'Giving the agent unrestricted root access and no limits on actions or iterations.',
    option_b: 'A bounded workspace (sandbox/branch), scoped file permissions, a maximum iteration cap, automated test verification, and human approval before any irreversible or external action (push, deploy, delete).',
    option_c: 'Never letting the agent run tests, only edit files.',
    option_d: 'Letting the agent skip tests whenever it wants to save time.',
    correct_answer: 'B',
    explanation: 'Safe autonomy = sandboxed environment + explicit action allowlist + iteration caps + verification (tests/lints) + human-in-the-loop for irreversible actions. This lets the agent be useful without risking data loss, security, or unbounded cost.',
    topic: 'Agentic AI',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-75',
    question: 'Which BEST describes how LoRA (Low-Rank Adaptation) fine-tuning works?',
    option_a: 'It freezes the pre-trained weights and learns small low-rank update matrices (A, B) such that W\u2019 = W + B*A, drastically reducing trainable parameters.',
    option_b: 'It retrains all model weights from scratch on the new dataset.',
    option_c: 'It only changes the tokenizer vocabulary, not the weights.',
    option_d: 'It replaces the attention mechanism entirely with a CNN.',
    correct_answer: 'A',
    explanation: 'LoRA injects trainable low-rank matrices A (d x r) and B (r x k) into each layer so the effective update is W + B*A with r much smaller than min(d, k). Base weights stay frozen, slashing trainable parameter count and memory while matching full fine-tuning on many tasks. Adapters can be swapped per task.',
    topic: 'GenAI',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-76',
    question: 'Which is the MOST accurate statement about embeddings and vector similarity for retrieval in RAG?',
    option_a: 'Cosine similarity on normalized embeddings measures the angle between vectors and is robust to magnitude differences; dot product on un-normalized vectors conflates similarity with magnitude.',
    option_b: 'Cosine similarity always returns the exact same ranking as Euclidean distance for all embeddings.',
    option_c: 'Embeddings of unrelated concepts are always orthogonal by construction.',
    option_d: 'Vector similarity does not require any indexing structure for large corpora.',
    correct_answer: 'A',
    explanation: 'Cosine similarity focuses on direction (angle), making it scale-invariant - useful when document embeddings vary in norm due to length. Dot product on un-normalized vectors biases toward high-norm vectors. For scale, ANN indexes (HNSW, IVF) are needed; "always orthogonal" and "exact same as Euclidean" are false in general.',
    topic: 'GenAI',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-77',
    question: 'In an agentic workflow, what is the role of a "critic" or "reflection" step, and why does it often improve final output quality?',
    option_a: 'It generates the initial answer so the worker can copy it.',
    option_b: 'It evaluates the draft against the task criteria and provides targeted feedback that the worker uses to revise, effectively adding search/planning depth at inference time without retraining.',
    option_c: 'It deletes the worker agent after each run.',
    option_d: 'It replaces the need for any prompt engineering.',
    correct_answer: 'B',
    explanation: 'Self-critique/reflection lets the agent score its own output against explicit criteria and revise, which is extra test-time compute that improves quality on hard tasks (like self-refine, reflexion). It does not replace prompting or training; it adds a verification+revision loop.',
    topic: 'Agentic AI',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-78',
    question: 'Which BEST explains the difference between fine-tuning, in-context learning, and retrieval-augmented generation (RAG) for injecting new knowledge into an LLM?',
    option_a: 'They are all identical and interchangeable.',
    option_b: 'Fine-tuning bakes knowledge/behavior into weights; in-context learning conditions behavior via examples in the prompt; RAG supplies fresh external facts at inference time without changing weights.',
    option_c: 'RAG permanently rewrites the model weights every query.',
    option_d: 'In-context learning requires retraining the model on a GPU cluster each time.',
    correct_answer: 'B',
    explanation: 'Fine-tuning updates weights (durable, slow, costly). In-context learning uses prompt examples to steer behavior at inference (no weight change, limited by context window). RAG retrieves external documents per query to ground answers in current/private data. They are complementary, not interchangeable.',
    topic: 'GenAI',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-79',
    question: 'In an agent that uses a tool-calling loop, which is the BEST way to prevent infinite tool-call cycles and runaway cost?',
    option_a: 'Remove all error handling so failures are silent.',
    option_b: 'Enforce a hard max-iteration/token budget per run, detect repeated failed/identical tool calls, and fall back to a safe default or hand off to a human when exceeded.',
    option_c: 'Give the agent unlimited API credits and no caps.',
    option_d: 'Disable all logging so cycles cannot be observed.',
    correct_answer: 'B',
    explanation: 'Agents can loop on failing tools or oscillate between actions. Hard caps (max steps/tokens), duplicate-action detection, and human fallback bound runtime and cost. Logging and error surfacing (not silencing) are essential for debugging and safety.',
    topic: 'Agentic AI',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
  {
    id: 'q-80',
    question: 'Which is the MOST accurate statement about "context window" limits in modern LLMs?',
    option_a: 'A larger context window always makes the model more accurate at every task with no downside.',
    option_b: 'Larger context allows more input but models can suffer "lost in the middle" attention degradation, higher latency/memory cost, and may still hallucinate facts that are present in the prompt.',
    option_c: 'Context window size has no effect on inference cost.',
    option_d: 'A model with a 128k context window always retrieves any fact in the context perfectly.',
    correct_answer: 'B',
    explanation: 'Long context helps fit large documents but is not free: attention can degrade for information in the middle of the prompt, latency and memory grow (KV-cache), and presence in context does not guarantee correct retrieval/generation. RAG/chunking often beats stuffing everything into context.',
    topic: 'GenAI',
    difficulty: 'Hard',
    is_active: true,
    created_at: ISO,
  },
];
// A/B/C/D (no more "always B") while keeping each question's order stable for scoring.
export const SAMPLE_QUESTIONS: Question[] = RAW_QUESTIONS.map(shuffleOptions);
